### ISSUE TITLE
CLI produces json instead of lcovonly when piping (not using `output`)

### ISSUE THREAD

**Issue by jessaustin** [SitePen/remap-istanbul#22]
I hope the following transcript is self-explanatory. CLI is producing the proper "lcovonly" format when using the `--output` option, but it's producing "json" when piped to e.g. `coveralls`. 
```bash
$ ./node_modules/.bin/remap-istanbul --input coverage/coverage.json --type lcovonly > output1
$ ./node_modules/.bin/remap-istanbul --input coverage/coverage.json --type lcovonly | cat > output2
$ ./node_modules/.bin/remap-istanbul --input coverage/coverage.json --type lcovonly --output output3
$ diff output1 output2
$ diff output1 output3 | head
1c1,43
< {"koa-signed-url.coffee":{"path":"koa-signed-url.coffee","statementMap":{"1":{"start":{"line":4,"column":0}...
---
> TN:
> SF:koa-signed-url.coffee
> FN:4,(anonymous_1)
> FN:11,(anonymous_2)
> FN:20,(anonymous_3)
> FN:34,(anonymous_4)
> FNF:4
```

**Comment by kitsonk** [comment]
Ok, this ended up being less of a bug than actually a design flaw.  It was not anticipated that all reports would be piped to stdout, so when `--output` was specified, `--type` would be considered, otherwise it would be ignored.  The `lcovonly` report is designed in Istanbul to be written to a file, but there is a `text-lcov` which is designed to be sent to stdout.  So the commit that will close this will accept either `--type lcovonly` or `--type text-lcov` and pipe those to stdout.  Otherwise it will silently fall through to outputting the JSON.

**Comment by jessaustin** [comment]
Thanks @kitsonk! Both for the fix and the npm release!
